add task2
vojtko84/altexsoft-lab-2020 pull request #3
Opened 2020-08-20 19:34 UTC by vojtko84

2020-09-01 08:21 UTC, alex-geraschenko commented
Почему оставили не реализованым `UnitOfWork`?
Он как раз призван решить проблему дублирования кода (чтение, запись, сериализация, десериализация) в Ваших контроллерах

2020-09-01 17:29 UTC, vojtko84 commented
Пробую реализовать UnitOfWork, но не получается, не могу понять как. В голове каша, запутался. Наверно необходимо возвращаться к отметке "старт" и начинать с нуля, расставив все на свои места.

2020-09-01 17:42 UTC, alex-geraschenko commented
Посмотрите тут пример реализации этих шаблонов https://www.infoworld.com/article/3107186/how-to-implement-the-repository-design-pattern-in-c.html

2020-09-01 17:49 UTC, vojtko84 commented
Ок, спасибо.

2020-09-14 16:31 UTC, alex-geraschenko requested changes

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.CMD/bin/Debug/netcoreapp3.1/ingredient.json
> +[{"Name":"\u041A\u0430\u0440\u0442\u043E\u0448\u043A\u0430","Amount":2},{"Name":"\u042F\u0439\u0446\u0430","Amount":4},{"Name":"\u0412\u043E\u0434\u0430","Amount":5},{"Name":"\u0420\u044B\u0431\u0430
Не хватает установки кодировки `Unicode` для консоли и сериализации

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Context/UnitOfWork.cs
> +    public class UnitOfWork
Для `UnitOfWork` стоит выделить интерфейс

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Context/UnitOfWork.cs
> +        public CategoryRepository CategoryRepository
Вместо класса лучше указывать интерфейс

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Controller/CategoryController.cs
> +        private UnitOfWork unitOfWork;
Стоит создать базовый класс и перенести туда `UnitOfWork` как `protected IUnitOfWork UnitOfWork;`

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Controller/IngredientController.cs
> +        public IngredientController(UnitOfWork unitOfWork)
Стоит создать базовый класс и перенести туда `UnitOfWork` как `protected IUnitOfWork UnitOfWork;`

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Controller/RecipeController.cs
> +        public RecipeController(UnitOfWork unitOfWork)
Стоит создать базовый класс и перенести туда `UnitOfWork` как `protected IUnitOfWork UnitOfWork;`

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Repository/CategoryRepository.cs
> +        private JsonContext db;
Стоит создать базовый класс и перенести туда `JsonContext` как `protected JsonContext Db;`

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Repository/IngredientRepository.cs
> +        private JsonContext db;
Стоит создать базовый класс и перенести туда `JsonContext` как `protected JsonContext Db;`

2020-09-14 16:31 UTC, alex-geraschenko commented on task2/CookBook/CookBook.BL/Repository/RecipeRepository.cs
> +        private JsonContext db;
Стоит создать базовый класс и перенести туда `JsonContext` как `protected JsonContext Db;`

2020-09-23 14:03 UTC, alex-geraschenko requested changes

2020-09-24 08:18 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-09-24 08:33 UTC, merged