Tasks/task3
vojtko84/altexsoft-lab-2020 pull request #4
Opened 2020-10-03 08:47 UTC by vojtko84

2020-10-05 19:28 UTC, alex-geraschenko requested changes
1. Файлы создания таблиц невозможно проверить, т.к. они сохранены в бинарном формате. Возможно из-за того, что первоначальная кодировка была `UTF-16`
2. В начале всех строк, которые Вы вставляете в колонки типа `NVARCHAR` следует добалять `N` перед началом строки: `N'Первые блюда'`

2020-10-06 09:39 UTC, alex-geraschenko requested changes

2020-10-06 09:39 UTC, alex-geraschenko commented on task3/schema/1Category.sql
> +	[Id] [int] IDENTITY(1,1) NOT NULL,
Эта структура не учитывает подкатегории. https://stackoverflow.com/questions/9409021/id-parentid-list-to-hierarchical-list

2020-10-06 09:39 UTC, alex-geraschenko commented on task3/queries/SQLQuery.sql
> +WHERE dbo.Recipe.CategoryId = 3)
Этот запрос не учитывает подкатегории. Посмотрите на **Common Table Expressions**

2020-10-06 09:39 UTC, alex-geraschenko commented on task3/schema/4RecipeIngredient.sql
> + CONSTRAINT [UQ_RecipeIngredient] UNIQUE NONCLUSTERED
Это ограничение избыточно. Первичный ключ сам по себе уникальный

2020-10-06 09:51 UTC, vojtko84 commented on task3/schema/1Category.sql
> +	[Id] [int] IDENTITY(1,1) NOT NULL,
Не учитывал подкатегории так как у меня во втором задании нет подкатегорий

2020-10-06 16:40 UTC, alex-geraschenko commented on task3/schema/1Category.sql
> +	[Id] [int] IDENTITY(1,1) NOT NULL,
Со вторым заданием - я не досмотрел. Пожалуйста, реализуйте с учетом подкатегорий как по ссылке выше

2020-10-06 16:57 UTC, vojtko84 commented on task3/schema/1Category.sql
> +	[Id] [int] IDENTITY(1,1) NOT NULL,
Ok, попробую реализовать с подкатегориями

2020-10-07 08:22 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-10-07 19:04 UTC, merged